# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
image: samueldebruyn/debian-git

pipelines:
  custom:
     deployment-to-demo:
       - step:
          script:
            - apt-get update
            - ssh ubuntu@webshop.dev.gingerpayments.com mkdir /home/ubuntu/zencart
            - scp -r ./* ubuntu@webshop.dev.gingerpayments.com:/home/ubuntu/zencart
            - ssh ubuntu@webshop.dev.gingerpayments.com sudo rsync -aP /home/ubuntu/zencart/* /var/www/html/zencart/
            - ssh ubuntu@webshop.dev.gingerpayments.com sudo cp /home/ubuntu/.env /var/www/html/zencart/includes/classes/vendors/ems-php/
            - ssh ubuntu@webshop.dev.gingerpayments.com sudo rm -rf /home/ubuntu/zencart
            - ssh ubuntu@webshop.dev.gingerpayments.com sudo chown -R www-data:www-data /var/www/html/zencart/